export const APP_WRITE_ID = 'nuxt-shop02'
export const DB_ID = 'shop-base'
export const COLLECTION_MAN = 'man-shoes'
export const COLLECTION_WOMAN = 'women-shoes'
export const COLLECTION_ORDERS = 'orders'
export const STORAGE_ID = 'storage'